### ISSUE TITLE
DvcAI公开页面文档列表

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/DvcAI-fe#10]
## DvcAI公开宣传页
查找需要网站底部footer一般放哪些协议链接，可调整添加以下内容：

- [x] 1. 帮助文档：使用DvcAI网站并编写帮助文档
- [x] 2. 使用条款：可参考MoModel
- [x] 3. 隐私政策：可参考MoModel

参考：

1. [MoModel](https://momodel.cn/)
2. [MoModel-使用条款](https://momodel.cn/docs/#/zh-cn/%E4%BD%BF%E7%94%A8%E6%9D%A1%E6%AC%BE)
3. [MoModel-隐私政策](https://momodel.cn/docs/#/zh-cn/%E9%9A%90%E7%A7%81%E6%94%BF%E7%AD%96)

**Comment by zmh530** [comment]
完成
