### ISSUE TITLE
DvcAI_v1.0.0待修改与添加内容

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/DvcAI-fe#12]
## 容器列表页

- [x] 1. 容器名改为“镜像名+容器id前8位”：后端需修改接口传来的信息 @JJLAAA 
- [x] 2. 容器支持改名：后端需添加修改容器信息的API @JJLAAA 
- [x] 3. 容器项显示容器所使用的基础镜像
- [x] 4. 管理员可选择主机运行容器，用户自动分配主机
- [x] 5. 容器布局调整：容器状态显示位置调整
- [x] 6. 容器删除后，列表没有立刻更新
- [x] 7. 删除容器时，需有确认提示 #14 
- [x] 8. 容器项的下载配置文件按钮与部署按钮调整

## 主机列表页
管理员可见，普通用户不可见。

- [x] 1. 主机item：需要后端API支持，可参考之前的tensorflow-docker-hub项目 @JJLAAA @Scisaga 

## 公开宣传页

- [x] 1. UI界面设计：PC端、手机端、Pad端 @NotkiDDo17 
- [x] 2. 插图设计：根据不同设备，需要不同比例插图显示 @NotkiDDo17 
- [x] 3. 页脚：帮助文档、用户协议、隐私政策
- [ ] 4. 前端开发：前端根据UI设计开发

## 其他

- [x] 1. 侧边栏添加svg背景：[svgbackgrounds](https://www.svgbackgrounds.com/)

**Comment by Scisaga** [comment]
主机相关接口代码实现已经提交，烦请部署测试 @JJLAAA @goodmornight 
Container增加字段proc_num：容器当前进程数量
