### ISSUE TITLE
个人信息管理页（只读）

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/DvcAI-fe#20]
将keycloak中可获得的信息显示出来：

1. 用户名
2. 用户姓名
3. 用户头像
4. 绑定邮箱
5. 关联账号
6. 用户权限

**Comment by Liuqianyik** [comment]
## 前期准备：
1.	把握好原本的代码结构
2.	学习vue-keycloak.js插件的调用方法，看看关于用户信息有没有更好的获取方法
3.	在Skote_vuejs这个UI模板中选择可用的组件
## 开发步骤：
1.	创建新分支，并命名为feature-profile
```
git status //检查当前源代码的状态，看看有没有新的修改什么的
git checkout -b feature-profile  //创建新分支并转到这个分支下
git branch  //查看当前项目的所有分支，并核对现在是否在刚才新建的子分支下
```
2.	给页头，头像下拉栏添加一个profile选项，点击效果就是跳转到个人信息管理页,更改这个文件即可
```
src/components/nav-bar.vue
```
3.	为即将添加的个人信息管理页配置路由
```js
//更改src/router/routes.js
{
    path: '/profile',
    name: '个人信息管理',
    meta: {
      authRequired: true,
    },
    component: () => import('./views/DvcAI/user/profile.vue'),
  },

```
4.	开始写个人信息管理页的组件
```
在src/router/views/DvcAI/这个文件夹下新建/user/profile.vue文件，然后开始开发（用到Skote_vuejs中筛选出来的可用组件）
```
5.	开发目标：
将keycloak获得的以下内容在个人信息管理页显示出来
a)	用户名
b)	用户姓名
c)	用户头像
d)	绑定邮箱
e)	关联账号
f)	用户权限

**Comment by Liuqianyik** [comment]
创建新分支feature-profile并提交到了远程，其中用户姓名，关联账号等信息用v-if判断，如果这些信息暂时不可获取，就先不显示这个信息
![image](https://user-images.githubusercontent.com/43923238/116229234-d4a66e80-a788-11eb-94f1-aee92cb88326.png)

**Comment by Liuqianyik** [comment]
对页面进行了优化，仿照github的卡片风格，共有四种布局可供参考
![image](https://user-images.githubusercontent.com/43923238/117757796-57ccc780-b253-11eb-9faa-6cca8229622a.png)
![image](https://user-images.githubusercontent.com/43923238/117757811-5ef3d580-b253-11eb-8a71-b14773046b57.png)
![image](https://user-images.githubusercontent.com/43923238/117757818-64512000-b253-11eb-8950-b6149790ec2c.png)
![image](https://user-images.githubusercontent.com/43923238/117757830-6d41f180-b253-11eb-9215-9ef4fee5cb13.png)
