### ISSUE TITLE
容器列表页面

### ISSUE THREAD

**Issue by Liuqianyik** [DvcLAB/DvcAI-fe#27]
- [x] 1.容器的JupyterLAB按钮不显示
- [x] 2.显示用户头像
- [x] 3.每个容器显示信息时，第一行的：容器名称，镜像，用户名称。靠近一些，统一靠左显示
- [x] 4.搜索容器框下面添加两个胶囊，可选择显示全部容器或者只显示运行中的容器（**需后端支持**） @JJLAAA 
- [x] 5.搜索容器选中之后的下拉框，现在显示的时容器id，把它换成：容器名称，镜像，用户。
- [x] 6.用户的容器状态，管理员要能够访问或者管理

![image](https://user-images.githubusercontent.com/43923238/115425921-a1b52580-a232-11eb-9cc4-625bacb0e285.png)

**Comment by goodmornight** [comment]
## 问题
1.容器的JupyterLAB按钮不显示
2.显示用户头像
3.每个容器显示信息时，第一行的：容器名称，镜像，用户名称。靠近一些，统一靠左显示
4.搜索容器框的右边加一个切换按钮，默认选择展示正在运行的容器，但是可以选择切换，查找全部容器
5.搜索容器选中之后的下拉框，现在显示的时容器id，把它换成：容器名称，镜像，用户。

## 解决
1. 昨天演示未显示JupyterLAB的原因是该容器并非我演示时的用户所创建，无法运行他人容器。
2. 已修改，并合并master分支提交
3. 已修改，并合并master分支提交
4. 已修改，**效果感觉有点奇怪，过滤切换需要后端接口支持**。（暂时未部署）

![image](https://user-images.githubusercontent.com/17687454/115555450-18f5c280-a2e2-11eb-81ae-6a518401a70b.png)

个人认为可以参考Kaggle：

图1：

![image](https://user-images.githubusercontent.com/17687454/115560835-8e17c680-a2e7-11eb-9b71-a2c54317d143.png)

图2：

![image](https://user-images.githubusercontent.com/17687454/115560935-a7207780-a2e7-11eb-8832-62e5a9da3588.png)

图3：

![image](https://user-images.githubusercontent.com/17687454/115560991-b3a4d000-a2e7-11eb-8b7c-844597901976.png)

5. 已修改，并合并master分支提交

**Comment by goodmornight** [comment]
## 问题
6.用户的容器状态，管理员要能够访问或者管理
## 解决
6. 已在前端添加管理员进入其他用户容器的”JupyterLAB“按钮，但需要后端权限控制支持 @linstein

**Comment by goodmornight** [comment]
## 问题
4.搜索容器框下面添加两个胶囊，可选择显示全部容器或者只显示运行中的容器
## 解决
4. 前端已添加至分支perf-container-list，等待后端接口完成，调整合并。
![image](https://user-images.githubusercontent.com/17687454/115953473-55adfd80-a51e-11eb-80b2-55c0c7d1f732.png)

**Comment by goodmornight** [comment]
## 问题
4.搜索容器框下面添加两个胶囊，可选择显示全部容器或者只显示运行中的容器（需后端支持）
## 解决
4. 已将后端接口添加，并合并至master分支，提交部署。
