### ISSUE TITLE
容器详情页

### ISSUE THREAD

**Issue by Liuqianyik** [DvcLAB/DvcAI-fe#28]
- [x] 1.增加修改容器名称的功能  #12 
- [x] 2.如果容器有gpu，就要添加gpu的使用情况并显示出来，如果有，显示启用，颜色用绿色（#008800），如果没有用gpu就不显示
- [x] 3.容器详情页具体布局再做一些调整
- [x] 4.右边的暂停按钮不要占整行，正常大小就好
- [x] 5.yaml文件的缩进问题以及其中的一些没用的空行要删掉
- [x] 6.dockerfile里面的代码应该可复制，右上角写一个复制按钮
- [x] 7.和dockerfile并列的再增加两个tab页：log,资源使用情况
- [x] 8.代码显示部分，效果调整一下，让它看起来更炫酷
- [x] 9.点击修改按钮之后不要重新布局，只把能修改的内容变成一个可输入的文本框，然后原本的内容在文本框里，然后文本框中的内容可修改，当它失焦就自动保存
- [x] 10.容器配置信息，第一行显示的镜像和下面一行没对齐
- [x] 11.右边三个按钮再大一点
- [x] 12.页面的字号再大一点
- [x] 13.dockerfile的主题样式再改的好看一点，灰色背景也在调整的好看一点

**Comment by goodmornight** [comment]
已修改，并部署
