### ISSUE TITLE
新增添加主机页面

### ISSUE THREAD

**Issue by Liuqianyik** [DvcLAB/DvcAI-fe#29]
需要新增一个添加主机的页面，还要能实现删除主机功能，只要知道【主机名称，主机IP，端口号，私钥】，通过接口调用，就可以远程ssh，将主机添加进来

**Comment by goodmornight** [comment]
添加主机页面前端已完成，已合并到master分支并部署，待测试 @JJLAAA @zmh530

**Comment by goodmornight** [comment]
添加主机页面已测试，可以正常使用。

**Comment by goodmornight** [comment]
已添加主机详情页，并可以删除主机，已部署，麻烦测试一下 @JJLAAA @zmh530
