### ISSUE TITLE
数据集列表页

### ISSUE THREAD

**Issue by Liuqianyik** [DvcLAB/DvcAI-fe#32]
- [x] 1.添加数据集时，要加入判定，判断这个链接是不是数据集，只有是数据集的情况才能添加进来，需要**后端协助添加接口** @JJLAAA

**Comment by JJLAAA** [comment]
没有与前端进行有效沟通，如果添加不合法的url的话，返回的是code 400

**Comment by goodmornight** [comment]
收到，我前端调整一下
