### ISSUE TITLE
其他

### ISSUE THREAD

**Issue by Liuqianyik** [DvcLAB/DvcAI-fe#36]
- [x] 1.页面刚开始加载的时候，默认显示的图片标准确定一下
- [x] 2.页面左上角dvc图片变大百分之五十
- [x] 3. 页面加载时，浏览器标签上的标题+描述

**Comment by goodmornight** [comment]
## 问题
1.页面刚开始加载的时候，默认显示的图片标准确定一下
2.页面左上角dvc图片变大百分之五十
3. 页面加载时，浏览器标签上的标题+描述
## 解决
1. 通过Vue组件方式实现，图片未加载出来前，默认显示`#ced6f5`颜色
2. 左上角logo大小已修改
3. 页面加载时，浏览器的标题和描述已修改
