### ISSUE TITLE
登录页面优化

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/DvcAI-fe#42]
- [x] 1. 背景特效目前无法显示，如果配置较为复杂，可使用左侧导航条的背景
- [x] 2. Sign in to your account 改为中文 **账户登录**
- [x] 3. 由于未进行i18n配置，可隐藏登录框右上角的多语言下拉框
- [x] 4. 微信和github图标默认彩色显示效果更好

**Comment by goodmornight** [comment]
已修改，并部署，麻烦测试一下 @zmh530 @linstein
