### ISSUE TITLE
项目列表页项目卡片高度不一致

### ISSUE THREAD

**Issue by zmh530** [DvcLAB/DvcAI-fe#43]
## 问题
项目列表页项目卡片高度不一致
![image](https://user-images.githubusercontent.com/78414223/117631987-6366b280-b1af-11eb-845b-da0662aa0cbd.png)
## 期望
项目列表页项目卡片高度一致

**Comment by goodmornight** [comment]
已修改，并部署，麻烦测试一下 @zmh530
