### ISSUE TITLE
镜像列表左侧默认图标

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/DvcAI-fe#46]
建议修改为：
![icons8-docker-container-96](https://user-images.githubusercontent.com/4192865/117783540-38df2d00-b275-11eb-87d9-c793d0a2d40c.png)

**Comment by goodmornight** [comment]
已修改，并部署，麻烦测试一下 @zmh530

**Comment by zmh530** [comment]
已测试，已部署完成。
