### ISSUE TITLE
登录页面Dvc图标修改

### ISSUE THREAD

**Issue by zmh530** [DvcLAB/DvcAI-fe#50]
## 问题
以Google Chrome为例，登录页面Dvc的logo在浏览器标签及收藏栏显示为白色。登陆后显示为粉橙渐变logo。
浏览器默认主题下难以辨认。通常的网页logo均为彩色，对比截图中其他logo可见。

![image](https://user-images.githubusercontent.com/78414223/118355678-d30be180-b5a3-11eb-8ba1-437046b89946.png)
## 解决

建议登录界面logo修改为登陆后的彩色logo。

**Comment by zmh530** [comment]
已修改。

**Comment by goodmornight** [comment]
已修改登录标签页的logo，麻烦确认一下 @zmh530

**Comment by zmh530** [comment]
已修改。
