### ISSUE TITLE
主机列表页面图标

### ISSUE THREAD

**Issue by zmh530** [DvcLAB/DvcAI-fe#51]
## 问题
主机列表页，主机详情条逻辑与容器列表页中容器详情相似。是否考虑风格进行统一。

1. 容器列表中每个容器前都有统一的、默认的容器icon。
2. 运行中使用中文“已运行”。
![image](https://user-images.githubusercontent.com/78414223/118356779-77445700-b5a9-11eb-82f4-40eff6c9b80b.png)
而主机列表并未进行统一。
且画面观感不太好，初步认为是右侧的四个图标的问题。没有容器列表“精而简”的感觉。
![image](https://user-images.githubusercontent.com/78414223/118356857-c2f70080-b5a9-11eb-8756-ab6963b63a24.png)
## 解决
建议进行统一，界面进行美化。

**Comment by Liuqianyik** [comment]
已修改并部署，麻烦测试一下 @zmh530

**Comment by zmh530** [comment]
已测试，部署完毕。
