### ISSUE TITLE
项目列表和数据集列表封面图片无法显示

### ISSUE THREAD

**Issue by youzi1030** [DvcLAB/DvcAI-fe#64]
![微信图片_20210709172904](https://user-images.githubusercontent.com/72690024/125057384-bee3ec80-e0db-11eb-92b6-e4b6f6ae7fdd.png)
![微信图片_20210709172856](https://user-images.githubusercontent.com/72690024/125057385-bf7c8300-e0db-11eb-996c-e11f405b6c46.png)

**Comment by Liuqianyik** [comment]
已修改， @zmh530 麻烦测试一下

**Comment by zmh530** [comment]
已测试，修改完毕。图片已可以正常显示。
