### ISSUE TITLE
用户头像下拉菜单功能更改

### ISSUE THREAD

**Issue by zmh530** [DvcLAB/DvcAI-fe#70]
- [x] 1. 用户头像下拉菜单添加【账户设置】，点击后可直接跳转至keycloak【编辑账户】页面，可进行用户名、密码等信息的修改。
![image](https://user-images.githubusercontent.com/78414223/126756038-ec700658-695a-4cd3-9fe4-5650d344c699.png)

- [ ] 2. 管理员头像下拉菜单【用户列表】更名为【用户管理】

**Comment by Liuqianyik** [comment]
已添加，待部署
![image](https://user-images.githubusercontent.com/43923238/126762374-ac125148-a394-46f2-8203-9ef10788ffcb.png)

**Comment by Liuqianyik** [comment]
已完成
