### ISSUE TITLE
镜像上传提示弹窗

### ISSUE THREAD

**Issue by zmh530** [DvcLAB/DvcAI-fe#71]
## 问题描述
用户点击上传镜像时，使用token判断用户是否补全用户名及密码，若用户名不合法或未补全密码，弹窗进行提示。
## 参照
[用户镜像上传流程](https://docs.google.com/presentation/d/1ZaFd6LG7pdxp19kb6lXW79Zdc8URYTjPPWBaSZDOJRo/edit#slide=id.ge532953a34_0_38)

**Comment by Liuqianyik** [comment]
已设置好弹窗界面，点击去设置会跳转到第二个界面，监听是否已设置密码的实现有待查证
![image](https://user-images.githubusercontent.com/43923238/126762034-7a4d71ae-3aea-4dfb-bc79-f2704c4539b4.png)

![image](https://user-images.githubusercontent.com/43923238/126762185-c7e3674f-5f06-4466-908a-2c93e5e01785.png)

**Comment by Liuqianyik** [comment]
逻辑需要更改
